{
  config,
  pkgs,
  ...
}: {
  # ---------------------------------------------------------------------------
  # HYPRLAND: NATIVE LUA COMPOSITOR CONFIGURATION
  # ---------------------------------------------------------------------------
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    # Compiles extraConfig directly into ~/.config/hypr/hyprland.lua in the Nix store
    configType = "lua";

    extraConfig = ''
      -- ======================================================================
      -- 1. DISPLAY ENGINE & SCANOUT PIPELINE
      -- ======================================================================
      hl.config({
        autogenerated = 0,

        -- Deterministic Hardware Binding:
        -- DP-2 locked to 1920x1080 @ 599.94Hz (0x0 coordinate offset, 1.0x scaling)
        -- eDP-1 is explicitly disabled when docked to free APU display engine bandwidth
        monitor = {
          "DP-2, 1920x1080@599.94, 0x0, 1",
          "eDP-1, disable",
        },

        -- Direct scanout bypasses composition passes on fullscreen surfaces
        render = {
          direct_scanout = true,
        },

        -- Master switch for wp_tearing_control_v1 protocol negotiation
        general = {
          allow_tearing = true,
          border_size = 2,
          gaps_in = 4,
          gaps_out = 8,
        },

        -- VFR Disabled: Continuous 600Hz polling eliminates display-wake latency
        debug = {
          vfr = false,
        },

        misc = {
          disable_hyprland_logo = true,
          disable_splash_rendering = true,
          force_default_wallpaper = 0,
          background_color = 0x000000,
        },

        decoration = {
          rounding = 0,
          shadow = { enabled = false },
          blur = { enabled = false },
        },
      })

      -- ======================================================================
      -- 2. HARDWARE SENSOR & 8000Hz POLLING INPUT PIPELINE
      -- ======================================================================
      hl.config({
        input = {
          sensitivity = 0.0,
          accel_profile = "flat", -- 1:1 raw bypass; eliminates libinput software curves
          touchpad = {
            disable_while_typing = true,
            natural_scroll = false,
          },
        },

        device = {
          {
            name = "compx-wireless-mouse-8k-dongle-l-mouse",
            sensitivity = 0.0,
            accel_profile = "flat",
          },
        },
      })

      -- ======================================================================
      -- 3. ASYNCHRONOUS TEARING WINDOW RULES (C++ ARRAY ENGINE)
      -- ======================================================================
      hl.config({
        windowrulev2 = {
          -- Rocket League (DX11 / Proton Swapchain)
          "immediate, class:^(rocketleague\\.exe)$",
          "immediate, class:^(steam_app_252950)$",
          "fullscreen_state 2 2, class:^(rocketleague\\.exe)$",
          "fullscreen_state 2 2, class:^(steam_app_252950)$",
          "workspace 5, class:^(rocketleague\\.exe)$",
          "workspace 5, class:^(steam_app_252950)$",

          -- osu! (Wine Staging / Low-Latency Audio Pipeline)
          "immediate, class:^(osu\\!\\.exe)$",
          "immediate, class:^(osu\\!)$",
          "fullscreen_state 2 2, class:^(osu\\!\\.exe)$",
          "fullscreen_state 2 2, class:^(osu\\!)$",
          "workspace 5, class:^(osu\\!\\.exe)$",
          "workspace 5, class:^(osu\\!)$",

          -- Counter-Strike 2 & Aim Lab
          "immediate, class:^(aimlab_tb\\.exe)$",
          "immediate, class:^(cs2)$",
          "workspace 5, class:^(aimlab_tb\\.exe)$",
          "workspace 5, class:^(cs2)$",
        },
      })

      -- ======================================================================
      -- 4. STARTUP PROCESSES & SYSTEM HOOKS (EXEC-ONCE)
      -- ======================================================================
      hl.config({
        exec_once = {
          "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1",
        },
        exec = {
          "systemctl --user restart kanshi",
        },
      })

      -- ======================================================================
      -- 5. NATIVE LUA KEYBINDINGS (C++ DISPATCHER INTERFACE)
      -- ======================================================================
      local mainMod = "SUPER"

      -- Core Dispatchers
      hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("${pkgs.kitty}/bin/kitty"))
      hl.bind(mainMod .. " + C", hl.dsp.window.close())
      hl.bind(mainMod .. " + M", hl.dsp.exit())
      hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
      hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
      hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("${pkgs.fuzzel}/bin/fuzzel"))
      hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("pkill -SIGUSR1 ironbar"))
      hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("screenshot-region"))

      -- Workspaces 1-5 Dispatcher Mapping
      for i = 1, 5 do
        hl.bind(mainMod .. " + " .. tostring(i), hl.dsp.focus({ workspace = tostring(i) }))
        hl.bind(mainMod .. " + SHIFT + " .. tostring(i), hl.dsp.window.move({ workspace = tostring(i) }))
      end

      -- Scroll Wheel Workspace Switching
      hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
      hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

      -- ======================================================================
      -- MOUSE WINDOW OPERATIONS (NATIVE C++ ARRAY ENGINE)
      -- ======================================================================
      hl.config({
        bindm = {
          "SUPER, mouse:272, movewindow",
          "SUPER, mouse:273, resizewindow",
        }
      })

      -- SwayOSD Audio & Brightness Integration
      hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --output-volume +5"))
      hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --output-volume -5"))
      hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --brightness raise"))
      hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --brightness lower"))

      -- Playerctl Media Controls
      hl.bind("XF86AudioMute", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --output-volume mute-toggle"))
      hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --input-volume mute-toggle"))
      hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl play-pause"))
      hl.bind("XF86AudioPause", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl play-pause"))
      hl.bind("XF86AudioNext", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl next"))
      hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl previous"))
    '';
  };

  # ---------------------------------------------------------------------------
  # INTERACTIVE SHELL & REBUILD PIPELINE
  # ---------------------------------------------------------------------------
  programs.git = {
    enable = true;
    settings.user = {
      name = "adenskyrp";
      email = "36445815+adenskyrp@users.noreply.github.com";
    };
  };

  programs.fish = {
    enable = true;
    functions = {
      sysdeploy = ''
        set -l current_dir $PWD
        cd ~/nixos-config

        git add .
        echo "--> Initiating declarative system rebuild..."
        if sudo nixos-rebuild switch --flake .#omnibook
          set -l commit_msg $argv
          if test -z "$commit_msg"
            set commit_msg "chore: automated system state update"
          end
          git commit -m "$commit_msg"
          echo "--> Pushing new generation to GitHub..."
          git push origin main
          echo "--> System successfully deployed and tracked."
        else
          echo "--> Build failed. Git commit aborted. Fix your Nix syntax."
        end

        cd $current_dir
      '';
    };
  };

  # ---------------------------------------------------------------------------
  # WAYLAND APPLICATION LAUNCHER (Fuzzel)
  # ---------------------------------------------------------------------------
  programs.fuzzel = {
    enable = true;
    settings = {
      main = {
        font = "FiraCode Nerd Font:size=13";
        terminal = "${pkgs.kitty}/bin/kitty";
        prompt = ''"❯ "'';
        layer = "top";
        lines = 10;
        width = 40;
        horizontal-pad = 20;
        vertical-pad = 20;
        inner-pad = 10;
      };
      colors = {
        background = "2e3440f2";
        text = "eceff4ff";
        match = "88c0d0ff";
        selection = "4c566aff";
        selection-text = "eceff4ff";
        border = "4c566aff";
      };
      border = {
        width = 2;
        radius = 8;
      };
    };
  };

  # ---------------------------------------------------------------------------
  # STATUS BAR & GTK3 LAYER-SHELL (Ironbar - Native XDG/Systemd Implementation)
  # ---------------------------------------------------------------------------
  xdg.configFile."ironbar/config.json".text = builtins.toJSON {
    anchor = {
      top = true;
      left = true;
      right = true;
      bottom = false;
    };
    layer = "top";
    height = 32;
    margin = {
      top = 4;
      left = 8;
      right = 8;
      bottom = 0;
    };

    start = [
      {
        type = "workspaces";
        all_monitors = false;
        name_map = {
          "1" = "1";
          "2" = "2";
          "3" = "3";
          "4" = "4";
          "5" = "5";
        };
      }
    ];

    end = [
      {
        type = "volume";
        format = "{icon} {percentage}%";
        max_volume = 100;
        on_scroll_up = "${pkgs.swayosd}/bin/swayosd-client --output-volume +2";
        on_scroll_down = "${pkgs.swayosd}/bin/swayosd-client --output-volume -2";
      }
      {
        type = "tray";
        icon_size = 16;
      }
      {
        type = "clock";
        format = "%H:%M";
      }
    ];
  };

  # Compiles GTK3 CSS into ~/.config/ironbar/style.css
  xdg.configFile."ironbar/style.css".text = ''
    /* Universal GTK Reset */
    * {
      font-family: "FiraCode Nerd Font", monospace;
      font-size: 13px;
      border: none;
      border-radius: 0;
      box-shadow: none;
      text-shadow: none;
      min-height: 0;
    }

    /* Target all root window variants to eliminate GTK theme white fallback */
    window,
    window.background,
    .bar,
    #bar {
      background-color: rgba(40, 44, 52, 0.95); /* Deep slate matching workspace container */
      color: #abb2bf;
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 8px;
      padding: 2px 6px;
    }

    .start, .center, .end {
      margin: 2px 0px;
    }

    /* Workspace Module Container */
    .workspaces {
      background-color: rgba(30, 34, 42, 0.7);
      border: 1px solid rgba(255, 255, 255, 0.05);
      border-radius: 6px;
      padding: 2px;
      margin-right: 8px;
    }

    /* Inactive Workspaces */
    .workspaces button,
    .workspaces .item {
      background: transparent;
      color: #abb2bf;
      padding: 2px 10px;
      border-radius: 4px;
      transition: all 120ms cubic-bezier(0.4, 0, 0.2, 1);
      font-weight: 500;
    }

    /* Interactive Hover State */
    .workspaces button:hover,
    .workspaces .item:hover {
      background-color: rgba(255, 255, 255, 0.12);
      color: #ffffff;
      cursor: pointer;
    }

    /* Active / Focused Workspace */
    .workspaces .item.focused,
    .workspaces .item.active,
    .workspaces .item.current {
      background-color: #ffffff;
      color: #1e222a;
      font-weight: 700;
    }

    /* Urgent Workspace Flag */
    .workspaces .item.urgent {
      background-color: #e06c75;
      color: #1e222a;
      font-weight: bold;
    }

    /* Right-Side Status Modules: High-contrast text on dark slate pills */
    .volume, .clock, .tray {
      background-color: rgba(30, 34, 42, 0.7);
      border: 1px solid rgba(255, 255, 255, 0.05);
      border-radius: 6px;
      padding: 2px 10px;
      margin-left: 6px;
      color: #ffffff;
    }

    .tray {
      padding: 2px 6px;
    }
  '';

  systemd.user.services.ironbar = {
    Unit = {
      Description = "Ironbar custom Wayland bar";
      After = ["graphical-session.target"];
      PartOf = ["graphical-session.target"];
    };
    Service = {
      ExecStart = "${pkgs.ironbar}/bin/ironbar";
      Restart = "on-failure";
      RestartSec = "1sec";
    };
    Install = {
      WantedBy = ["hyprland-session.target"];
    };
  };

  # ---------------------------------------------------------------------------
  # LOW-LATENCY EDITOR (Neovim)
  # ---------------------------------------------------------------------------
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    withPython3 = false;
    withRuby = false;

    extraPackages = with pkgs; [
      nixd
      alejandra
      ripgrep
      fd
    ];

    plugins = with pkgs.vimPlugins; [
      nvim-treesitter.withAllGrammars
      nvim-lspconfig
      telescope-nvim
      plenary-nvim
    ];

    initLua = ''
      vim.opt.clipboard = "unnamedplus"
      vim.g.mapleader = " "
      vim.opt.number = true
      vim.opt.relativenumber = true
      vim.opt.shiftwidth = 2
      vim.opt.tabstop = 2
      vim.opt.expandtab = true
      vim.opt.updatetime = 50

      vim.lsp.config('nixd', {
        cmd = { "nixd" },
        settings = {
          nixd = {
            formatting = { command = { "alejandra" } },
          },
        },
      })
      vim.lsp.enable('nixd')

      vim.api.nvim_create_autocmd("BufWritePre", {
        pattern = "*.nix",
        callback = function()
          vim.lsp.buf.format()
        end,
      })

      local builtin = require('telescope.builtin')
      vim.keymap.set('n', '<leader>f', builtin.find_files, {})
      vim.keymap.set('n', '<leader>g', builtin.live_grep, {})
    '';
  };

  # ---------------------------------------------------------------------------
  # BROADCAST & CAPTURE PIPELINE (OBS Studio)
  # ---------------------------------------------------------------------------
  programs.obs-studio = {
    enable = true;
    plugins = with pkgs.obs-studio-plugins; [
      obs-vkcapture
      obs-pipewire-audio-capture
      obs-vaapi
      obs-gstreamer
    ];
  };

  # ---------------------------------------------------------------------------
  # DECLARATIVE BROWSER (Firefox)
  # ---------------------------------------------------------------------------
  programs.firefox = {
    enable = true;
    configPath = "${config.xdg.configHome}/mozilla/firefox";

    policies = {
      DisableTelemetry = true;
      DisableFirefoxStudies = true;
      DisablePocket = true;
      OverrideFirstRunPage = "";
      OverridePostUpdatePage = "";

      EnableTrackingProtection = {
        Value = true;
        Locked = true;
        Cryptomining = true;
      };

      ExtensionSettings = {
        "*" = {installation_mode = "allowed";};
        "uBlock0@raymondhill.net" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi";
          installation_mode = "force_installed";
        };
        "{d8293796-0370-4f51-b845-89498a442750}" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/youtube-music-enhancer/latest.xpi";
          installation_mode = "force_installed";
        };
      };
    };

    profiles.crazycat = {
      id = 0;
      isDefault = true;

      settings = {
        "gfx.webrender.all" = true;
        "gfx.webrender.compositor" = true;
        "gfx.webrender.compositor.force-enabled" = true;
        "widget.use-aspect-ratio" = true;
        "widget.dmabuf.wayland-hardware-efficient" = true;
        "media.ffmpeg.vaapi.enabled" = true;
        "media.hardware-video-decoding.enabled" = true;
        "media.av1.enabled" = true;
        "layers.acceleration.force-enabled" = true;

        "layout.frame_rate" = 0;
        "apz.overscroll.enabled" = true;
        "nglayout.initialpaint.delay" = 0;
        "browser.preferences.defaultPerformanceSettings.enabled" = false;
        "image.mem.shared" = true;

        "browser.cache.disk.enable" = true;
        "browser.cache.disk.capacity" = 1048576;
        "browser.cache.memory.enable" = true;

        "extensions.pocket.enabled" = false;
        "browser.newtabpage.activity-stream.showSponsored" = false;
        "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
        "browser.newtabpage.activity-stream.feeds.telemetry" = false;
        "toolkit.telemetry.enabled" = false;
        "browser.ping-centre.telemetry" = false;
        "browser.compactmode.show" = true;
        "browser.uidensity" = 1;
        "browser.tabs.firefox-view" = false;
      };
    };
  };

  # ---------------------------------------------------------------------------
  # USER-SPACE PACKAGES & LOW-LATENCY HELPERS
  # ---------------------------------------------------------------------------
  fonts.fontconfig.enable = true;

  home.packages = with pkgs; [
    nerd-fonts.fira-code
    pavucontrol
    deepfilternet
    lsp-plugins
    polkit_gnome
    docker-client
    playerctl
    overskride
    wineWow64Packages.staging
    winetricks
    protontricks
    grim
    slurp
    wl-clipboard
    satty
    adwaita-icon-theme
    hicolor-icon-theme
    obs-studio-plugins.obs-vkcapture
    libva-utils
    osu-lazer-bin
    celluloid

    (discord.override {
      withVencord = true;
      withOpenASAR = true;
    })

    (writeShellScriptBin "screenshot-region" ''
      SCREENSHOT_DIR="$HOME/Pictures/Screenshots"
      mkdir -p "$SCREENSHOT_DIR"
      FILENAME="$SCREENSHOT_DIR/$(date +'%Y-%m-%d_%H-%M-%S').png"

      ${pkgs.grim}/bin/grim -g "$(${pkgs.slurp}/bin/slurp)" - | tee "$FILENAME" | ${pkgs.wl-clipboard}/bin/wl-copy
      if command -v notify-send &> /dev/null; then
        notify-send "Screenshot Captured" "Saved to $FILENAME and copied to clipboard." --icon=camera
      fi
    '')

    (writeShellScriptBin "osu-launcher" ''
      export WINEPREFIX="$HOME/.wine-osu"
      export STAGING_AUDIO_DURATION="10000"
      export STEAM_COMPAT_DATA_PATH="$HOME/.wine-osu"
      export PIPEWIRE_LATENCY="64/48000"
      export DXVK_HUD=0

      server_input=$(echo "" | ${pkgs.fuzzel}/bin/fuzzel -d -p "osu! DevServer (Leave blank for Bancho): ")

      if [ -n "$server_input" ]; then
        exec obs-gamecapture ${pkgs.wineWow64Packages.staging}/bin/wine "$HOME/Games/osu/osu!.exe" -devserver "$server_input" "$@"
      else
        exec obs-gamecapture ${pkgs.wineWow64Packages.staging}/bin/wine "$HOME/Games/osu/osu!.exe" "$@"
      fi
    '')
  ];

  services.swayosd = {
    enable = true;
    stylePath = null;
  };

  # ---------------------------------------------------------------------------
  # DYNAMIC OUTPUT MANAGEMENT (Kanshi Daemon)
  # ---------------------------------------------------------------------------
  services.kanshi = {
    enable = true;
    systemdTarget = "hyprland-session.target";
    settings = [
      {
        profile = {
          name = "docked";
          outputs = [
            {
              criteria = "eDP-1";
              status = "disable";
            }
            {
              criteria = "BNQ XL2586X+ EB3CR02979SL0";
              mode = "1920x1080@599.94Hz";
              position = "0,0";
              scale = 1.0;
              status = "enable";
            }
          ];
        };
      }
      {
        profile = {
          name = "undocked";
          outputs = [
            {
              criteria = "eDP-1";
              mode = "2240x1400@60.00Hz";
              position = "0,0";
              scale = 1.4583334;
              status = "enable";
            }
          ];
        };
      }
    ];
  };

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    settings = {
      "*" = {
        ServerAliveInterval = 30;
        ServerAliveCountMax = 3;
        TCPKeepAlive = "yes";
      };
    };
  };

  # ---------------------------------------------------------------------------
  # XDG MIME ROUTING & THEMES
  # ---------------------------------------------------------------------------
  xdg.desktopEntries = {
    osu-stable = {
      name = "osu!stable";
      exec = "osu-launcher %U";
      icon = "osu!";
      comment = "osu! stable";
      terminal = false;
      categories = ["Game"];
      mimeType = [
        "application/x-osu-beatmap"
        "application/x-osu-skin"
        "application/x-osu-replay"
        "application/x-extension-osz"
        "application/x-extension-osk"
        "application/x-extension-osr"
      ];
    };
  };

  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "application/x-osu-beatmap" = "osu-stable.desktop";
      "application/x-osu-skin" = "osu-stable.desktop";
      "application/x-osu-replay" = "osu-stable.desktop";
      "application/x-extension-osz" = "osu-stable.desktop";
      "application/x-extension-osk" = "osu-stable.desktop";
      "application/x-extension-osr" = "osu-stable.desktop";
    };
  };

  gtk = {
    enable = true;
    gtk4.theme = null;
    theme = {
      name = "Adwaita-dark";
      package = pkgs.gnome-themes-extra;
    };
    iconTheme = {
      name = "Adwaita";
      package = pkgs.adwaita-icon-theme;
    };
  };

  home.sessionVariables = {
    MOZ_USE_XDG = "1";
  };

  home.stateVersion = "25.11";
}
