{
  config,
  pkgs,
  ...
}: {
  # ---------------------------------------------------------------------------
  # HYPRLAND: NATIVE LUA COMPOSITOR CONFIGURATION
  # ---------------------------------------------------------------------------
  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;

    # Compiles extraConfig directly into ~/.config/hypr/hyprland.lua in the Nix store
    configType = "lua";

    extraConfig = ''
      -- ======================================================================
      -- 1. DISPLAY ENGINE & SCANOUT PIPELINE
      -- ======================================================================
      hl.config({
        autogenerated = 0,

        -- Deterministic Hardware Binding:
        -- The output is DP-1, confirmed by `hyprctl monitors`. This rule named
        -- DP-2 until 2026-08-27 and was therefore dead. Note DP-2 is not a
        -- typo for a nonexistent connector -- it genuinely exists in the DRM
        -- topology, because the panel hangs off a DisplayPort MST hub and the
        -- adapter exposes a second branch. The log shows it as
        --   drm: connector DP-2, has crtc -1, will be rechecked
        -- i.e. present but with no CRTC assigned, so no monitor rule for it can
        -- ever apply. A dead rule that names a real connector is worse than one
        -- naming a fake, since grepping for the name finds it and the rule looks
        -- live.
        --
        -- kanshi is the authority for mode setting (it matches on the EDID
        -- string, which survives connector renumbering across MST re-enumeration
        -- in a way DP-N does not). This rule is a deliberate fallback so
        -- Hyprland comes up at the right mode before kanshi's profile lands --
        -- with the rule dead, startup did eDP-1@60 -> DP-1@60 -> DP-1@599.94,
        -- i.e. an extra modeset that kanshi had to correct. The duplication is
        -- intentional, not drift.
        --
        -- eDP-1 is explicitly disabled when docked to free APU display engine
        -- bandwidth.
        monitor = {
          "DP-1, 1920x1080@599.94, 0x0, 1",
          "eDP-1, disable",
        },

        -- Direct scanout hands the client's buffer straight to the display
        -- controller, skipping the compositor's blend pass entirely. Measured
        -- 2026-08-27: with ironbar mapped this output was pulling 8872 MB/s DRAM
        -- reads; killing ironbar dropped it to 4230 MB/s, which is close to one
        -- 1920x1080x4 framebuffer read per refresh (1920*1080*4*600 = 4977 MB/s)
        -- -- i.e. what remains is the composite pass itself. Scanout is the lever
        -- that removes that, on a bus the APU shares with the CPU.
        --
        -- This is an INT, not a bool (`hyprctl getoption render:direct_scanout`
        -- reports `int: 0`): 0 = off, 1 = on, 2 = auto. Writing `true` here would
        -- be a type error or a silent coercion.
        --
        -- 1 rather than 2 deliberately. `auto` gates on the client tagging its
        -- surface via wp_content_type_v1 (Hyprland 0.56.2 does implement the
        -- protocol), and whether osu! lazer sets that hint is unverified -- so 2
        -- risks being a silent no-op, which is the failure mode this repo keeps
        -- getting bitten by. 1 attempts scanout for any eligible fullscreen
        -- surface and is unambiguous.
        --
        -- Preconditions, all of which must hold simultaneously: fullscreen (the
        -- osu! window rules set fullscreen_state = "2 2"), a single opaque
        -- surface, and NO mapped layer surface on the output -- which is why
        -- ironbar has to be stopped, not merely hidden. swayosd-server maps a
        -- surface when a volume/brightness OSD appears, so expect a transient
        -- scanout drop on those keypresses; that is acceptable and not worth
        -- fixing.
        render = {
          direct_scanout = 0,
        },

        -- HARDWARE CURSORS ARE KEPT ON, AND THIS CONFLICTS WITH TEARING. Read
        -- before changing either this or render.direct_scanout above.
        --
        -- The comment that stood here until 2026-08-27 argued at length that
        -- software cursors were required for wp_tearing_control_v1 to engage,
        -- citing a runtime log line:
        --   tearingBlockedBy: next frame is not torn, missing candidate, hw cursor
        -- That line does not appear anywhere in the current Hyprland log, at any
        -- point, including with osu! running. It is unverified, so the reasoning
        -- is recorded as a claim rather than as fact. `tearingBlockedBy` is only
        -- emitted when a tearing page-flip is actually attempted, so the check
        -- has to be run with a fullscreen tearing client VISIBLE on DP-1:
        --   grep -iE 'tearing|torn|blocked' \
        --     $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log
        --
        -- What IS confirmed from the log is that hardware cursors win today:
        --   aquamarine: drm: Cursor buffer imported into KMS with id 519/520
        --
        -- The two goals pull in opposite directions, and that is the real reason
        -- to leave this alone. A software cursor is composited INTO the frame,
        -- which means the surface handed to the display controller is no longer
        -- the client's unmodified buffer -- so software cursors DEFEAT direct
        -- scanout. Scanout is worth ~4.2 GB/s of measured shared bandwidth;
        -- tearing is worth up to one frame of latency at 1.67 ms and is
        -- currently unverified. Keeping the hardware cursor plane (2 = auto,
        -- which resolves to HW here) buys the measured win over the speculative
        -- one. Do not flip this to 1 to chase tearing without first confirming
        -- tearing is actually blocked, and accepting the scanout loss.
        cursor = {
          -- Renamed upstream: the key is `no_hardware_cursors` on Hyprland 0.56,
          -- and it is an int (0 = HW cursors, 1 = never, 2 = auto), not a bool.
          no_hardware_cursors = 2,
        },

        -- Master switch for wp_tearing_control_v1 protocol negotiation
        general = {
          allow_tearing = true,
          border_size = 1,
          gaps_in = 0,
          gaps_out = 0,
        },

        -- VFR left at its default (enabled). It governs whether Hyprland skips
        -- redrawing an idle *desktop*, not how the game's frames reach the
        -- display -- once direct scanout takes over the fullscreen surface,
        -- in-game latency comes from the tearing/immediate/scanout trio above.
        -- Forcing it off only burned shared-TDP headroom redrawing the bar.

        misc = {
          disable_hyprland_logo = true,
          disable_splash_rendering = true,
          force_default_wallpaper = 0,
          background_color = 0x000000,
        },

        decoration = {
          rounding = 0,
          shadow = { enabled = false },
          blur = { enabled = false },
        },
      })

      -- ======================================================================
      -- 2. HARDWARE SENSOR & 8000Hz POLLING INPUT PIPELINE
      -- ======================================================================
      hl.config({
        input = {
          sensitivity = 0.0,
          accel_profile = "flat", -- 1:1 raw bypass; eliminates libinput software curves
          touchpad = {
            disable_while_typing = true,
            natural_scroll = false,
          },
        },

        device = {
          {
            name = "compx-wireless-mouse-8k-dongle-l-mouse",
            sensitivity = 0.0,
            accel_profile = "flat",
          },
        },
      })

      -- ======================================================================
      -- 3. ASYNCHRONOUS TEARING & WORKSPACE RULES (NATIVE LUA TABLE API)
      -- ======================================================================
      -- Bypasses deprecated windowrulev2 string parsers. Tables are compiled
      -- directly into internal CWindowRule structs by the Hyprland Lua engine.

      -- Rocket League (DX11 / Proton Swapchain)
      hl.window_rule({
        match = { class = "rocketleague.exe" },
        immediate = true,          -- Triggers wp_tearing_control_v1 async scanout
        no_anim = true,           -- snake_case per Hyprland Lua API (not "noanim")
        fullscreen_state = "2 2",  -- Forces client + compositor exclusive fullscreen
        tile = true,
        workspace = 5,
      })
      hl.window_rule({
        match = { class = "steam_app_252950" },
        immediate = true,
        no_anim = true,
        fullscreen_state = "2 2",
        tile = true,
        workspace = 5,
      })

      -- osu! (Wine Staging / Direct Latency Pipeline)
      hl.window_rule({
        match = { class = "osu!\\.exe" },
        immediate = true,
        no_anim = true,
        fullscreen_state = "2 2",
        tile = true,
        workspace = 5,
      })
      hl.window_rule({
        match = { class = "osu!" },
        immediate = true,
        no_anim = true,
        fullscreen_state = "2 2",
        tile = true,
        workspace = 5,
      })

      -- Counter-Strike 2 & Aim Lab
      hl.window_rule({
        match = { class = "aimlab_tb.exe" },
        immediate = true,
        no_anim = true,
        tile = true,
        workspace = 5,
      })
      hl.window_rule({
        match = { class = "cs2" },
        immediate = true,
        no_anim = true,
        tile = true,
        workspace = 5,
      })
      -- ======================================================================
      -- 4. STARTUP PROCESSES & SYSTEM HOOKS (EXEC-ONCE)
      -- ======================================================================
      -- `exec` (as opposed to `exec_once`) fires on EVERY Hyprland config
      -- reload, and it used to carry "systemctl --user restart kanshi". A kanshi
      -- restart re-applies the output profile, which can trigger a modeset --
      -- and a modeset at 599.94 Hz across a DisplayPort MST link is a
      -- multi-second black-and-recover, which matches the reported symptom
      -- ("dropping to really low FPS for a short amount of time, similar to
      -- unplugging it from the wall and plugging it back in") closely enough to
      -- be a prime suspect for the drops themselves.
      --
      -- It was redundant as well as harmful: services.kanshi.systemdTarget is
      -- set to hyprland-session.target, so the unit already starts with the
      -- session and needs no help from here.
      hl.config({
        exec_once = {
          "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1",
        },
      })

      -- ======================================================================
      -- 5. NATIVE LUA KEYBINDINGS (C++ DISPATCHER INTERFACE)
      -- ======================================================================
      local mainMod = "SUPER"

      -- Core Dispatchers
      hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("${pkgs.kitty}/bin/kitty"))
      hl.bind(mainMod .. " + C", hl.dsp.window.close())
      hl.bind(mainMod .. " + M", hl.dsp.exit())
      hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
      hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
      hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("${pkgs.fuzzel}/bin/fuzzel"))
      -- Toggles the ironbar UNIT, not the process. Two reasons:
      --
      -- This bind was `pkill -SIGUSR1 ironbar`. SIGUSR1 is *waybar's* toggle
      -- signal; ironbar installs no handler for it, so the default disposition
      -- (terminate) applied. SIGUSR1 is not in systemd's default
      -- SuccessExitStatus signal set, so systemd scored the death as a failure,
      -- and Restart=on-failure + RestartSec=1sec brought the bar back exactly
      -- one second later -- the reported "pops back up". (Plain `pkill ironbar`
      -- stuck by contrast, because SIGTERM *is* in the default success set:
      -- confirmed `code=killed, signal=TERM`, unit stayed inactive (dead).)
      --
      -- Stopping the unit is also the only form that survives the next
      -- hyprland-session.target reload, and -- the part that matters for
      -- render.direct_scanout above -- it actually UNMAPS the layer surface.
      -- Scanout requires no mapped layer surface on the output, so a bar that
      -- is merely hidden or restarted does not free the scanout path.
      hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(
        "systemctl --user is-active --quiet ironbar && systemctl --user stop ironbar || systemctl --user start ironbar"
      ))
      -- Screenshot lived on SUPER + SHIFT + S until 2026-08-30. It moved here to
      -- free that chord for the special-workspace move below, which is where
      -- upstream's own bundled example config puts it. PRINT was unbound, and is
      -- the obvious home for a screenshot key anyway.
      hl.bind("PRINT", hl.dsp.exec_cmd("screenshot-region"))

      -- Workspaces 1-5 Dispatcher Mapping
      for i = 1, 5 do
        hl.bind(mainMod .. " + " .. tostring(i), hl.dsp.focus({ workspace = tostring(i) }))
        hl.bind(mainMod .. " + SHIFT + " .. tostring(i), hl.dsp.window.move({ workspace = tostring(i) }))
      end

      -- Special ("magic") Workspace -- the scratchpad overlay
      --
      -- A special workspace is not one of the numbered ones. It renders as an
      -- overlay ON TOP of whichever workspace is currently active, and toggling
      -- it away leaves that underlying workspace focused and untouched -- no
      -- workspace switch, so nothing below it gets re-tiled or re-focused. That
      -- is what makes it usable mid-game: flash up a terminal or a chat window
      -- over Rocket League and dismiss it without the game's workspace ever
      -- changing under it.
      --
      -- "magic" is just the workspace's name -- any string works. The only
      -- requirement is that the two binds agree, and note they spell it
      -- differently on purpose: toggle_special takes the BARE name, while the
      -- window-move dispatcher takes the QUALIFIED `special:magic`, because it
      -- accepts ordinary workspaces too and needs the prefix to disambiguate.
      --
      -- These are the native Lua dispatchers, matching upstream's bundled
      -- example config for 0.56.2. The `togglespecialworkspace` / `movetoworkspace`
      -- spellings in the Hyprland wiki are hyprland.conf syntax and do not apply
      -- to this file -- see the mouse binds below for what happens when
      -- hyprland.conf syntax is pasted into a Lua config.
      hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
      hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

      -- Scroll Wheel Workspace Switching
      hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
      hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

      -- ======================================================================
      -- MOUSE WINDOW OPERATIONS (NATIVE C++ ARRAY ENGINE)
      -- ======================================================================
      hl.config({
        bindm = {
          "SUPER, mouse:272, movewindow",
          "SUPER, mouse:273, resizewindow",
        }
      })

      -- SwayOSD Audio & Brightness Integration
      hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --output-volume +5"))
      hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --output-volume -5"))
      hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --brightness raise"))
      hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --brightness lower"))

      -- Playerctl Media Controls
      hl.bind("XF86AudioMute", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --output-volume mute-toggle"))
      hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("${pkgs.swayosd}/bin/swayosd-client --input-volume mute-toggle"))
      hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl play-pause"))
      hl.bind("XF86AudioPause", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl play-pause"))
      hl.bind("XF86AudioNext", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl next"))
      hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("${pkgs.playerctl}/bin/playerctl previous"))
    '';
  };

  # ---------------------------------------------------------------------------
  # INTERACTIVE SHELL & REBUILD PIPELINE
  # ---------------------------------------------------------------------------
  programs.git = {
    enable = true;
    settings.user = {
      name = "adenskyrp";
      email = "36445815+adenskyrp@users.noreply.github.com";
    };
  };

  programs.fish = {
    enable = true;
    functions = {
      sysdeploy = ''
        set -l current_dir $PWD
        cd ~/nixos-config

        git add .
        echo "--> Initiating declarative system rebuild..."
        if sudo nixos-rebuild switch --flake .#omnibook
          set -l commit_msg $argv
          if test -z "$commit_msg"
            set commit_msg "chore: automated system state update"
          end
          git commit -m "$commit_msg"
          echo "--> Pushing new generation to GitHub..."
          git push origin main
          echo "--> System successfully deployed and tracked."
        else
          echo "--> Build failed. Git commit aborted. Fix your Nix syntax."
        end

        cd $current_dir
      '';
    };
  };

  # ---------------------------------------------------------------------------
  # WAYLAND APPLICATION LAUNCHER (Fuzzel)
  # ---------------------------------------------------------------------------
  programs.fuzzel = {
    enable = true;
    settings = {
      main = {
        font = "FiraCode Nerd Font:size=13";
        terminal = "${pkgs.kitty}/bin/kitty";
        prompt = ''"❯ "'';
        layer = "top";
        lines = 10;
        width = 40;
        horizontal-pad = 20;
        vertical-pad = 20;
        inner-pad = 10;
      };
      colors = {
        background = "2e3440f2";
        text = "eceff4ff";
        match = "88c0d0ff";
        selection = "4c566aff";
        selection-text = "eceff4ff";
        border = "4c566aff";
      };
      border = {
        width = 2;
        radius = 8;
      };
    };
  };

  # ---------------------------------------------------------------------------
  # STATUS BAR & GTK3 LAYER-SHELL (Ironbar - Native XDG/Systemd Implementation)
  # ---------------------------------------------------------------------------
  xdg.configFile."ironbar/config.json".text = builtins.toJSON {
    anchor = {
      top = true;
      left = true;
      right = true;
      bottom = false;
    };
    layer = "top";
    height = 32;
    margin = {
      top = 0;
      left = 0;
      right = 0;
      bottom = 0;
    };

    start = [
      {
        type = "workspaces";
        all_monitors = false;
        name_map = {
          "1" = "1";
          "2" = "2";
          "3" = "3";
          "4" = "4";
          "5" = "5";
        };
      }
    ];

    end = [
      {
        type = "volume";
        format = "{icon} {percentage}%";
        max_volume = 100;
        on_scroll_up = "${pkgs.swayosd}/bin/swayosd-client --output-volume +2";
        on_scroll_down = "${pkgs.swayosd}/bin/swayosd-client --output-volume -2";
      }
      {
        type = "tray";
        icon_size = 16;
      }
      {
        type = "clock";
        format = "%H:%M";
      }
    ];
  };

  # Compiles GTK4 CSS into ~/.config/ironbar/style.css. ironbar 0.19 links
  # gtk4-4.22.4 -- this said GTK3 until 2026-08-27, which is also why the
  # GSK_RENDERER lever on the unit below works at all (GSK is GTK4-only; GTK3
  # has no such renderer selection).
  xdg.configFile."ironbar/style.css".text = ''
    /* Universal GTK Reset */
    * {
      font-family: "FiraCode Nerd Font", monospace;
      font-size: 13px;
      border: none;
      border-radius: 0;
      box-shadow: none;
      text-shadow: none;
      min-height: 0;
    }

    /* Root bar surface.
     *
     * The three properties below are COMPOSITING-COST choices, not aesthetic
     * ones -- do not "restore" them without reading this.
     *
     * A layer surface that is fully opaque and rectangular lets the compositor
     * take its opaque-region shortcut: it knows nothing behind the bar is
     * visible, so it skips both the blend pass and the work of drawing what is
     * underneath. Three things defeated that here:
     *   - background-color alpha 0.95  -> non-opaque, forces a blend pass
     *   - border-radius 8px            -> not rectangular, no opaque region
     *   - transition on .item:hover    -> repaint churn on pointer movement
     *
     * At 599.94 Hz that cost is paid up to 600 times a second. Measured
     * 2026-08-27, ironbar mapped vs stopped: DRAM reads 8872 -> 4230 MB/s,
     * writes 3986 -> 1104 MB/s, GPU power 19 -> 13 W, GFX_SCLK 1643 -> 941 MHz.
     * Opaque and square is what makes the bar cheap for the times it IS mapped;
     * stopping the unit (SUPER+D) is what frees direct scanout entirely.
     *
     * Child elements (.item, module backgrounds) keep their alpha deliberately.
     * Those blend inside GTK against an opaque root, on the CPU now that the
     * renderer is Cairo, and do not change the surface opaque region the
     * compositor reasons about. Only the ROOT surface needed to become opaque
     * and rectangular -- there is no reason to strip the rest of the styling.
     */
    window,
    window.background,
    .bar,
    #bar {
      background-color: rgb(40, 44, 52);
      color: #abb2bf;
      border: 1px solid rgb(56, 60, 70);
      border-radius: 0;
      padding: 2px 6px;
    }

    .start, .center {
      margin: 2px 0px;
    }

    /* Left-Side Container: Workspaces */
    .workspaces {
      background-color: rgba(30, 34, 42, 0.7);
      border: 1px solid rgba(255, 255, 255, 0.05);
      border-radius: 6px;
      padding: 2px;
      margin-right: 8px;
    }

    /* Inactive Workspaces */
    .workspaces button,
    .workspaces .item {
      background: transparent;
      color: #abb2bf;
      padding: 2px 10px;
      border-radius: 4px;
      font-weight: 500;
    }

    /* Interactive Hover State */
    .workspaces button:hover,
    .workspaces .item:hover {
      background-color: rgba(255, 255, 255, 0.12);
      color: #ffffff;
      cursor: pointer;
    }

    /* Active / Focused Workspace (High-Contrast White Highlight) */
    .workspaces .item.focused,
    .workspaces .item.active,
    .workspaces .item.current {
      background-color: #ffffff;
      color: #1e222a;
      font-weight: 700;
    }

    /* Urgent Workspace Notification Flag */
    .workspaces .item.urgent {
      background-color: #e06c75;
      color: #1e222a;
      font-weight: bold;
    }

    /* Right-Side Container: Audio, Clock & Tray (Mirrors .workspaces) */
    .end {
      background-color: rgba(30, 34, 42, 0.7);
      border: 1px solid rgba(255, 255, 255, 0.05);
      border-radius: 6px;
      padding: 2px 4px;
      margin: 2px 0px;
    }

    /* Nested Status Widgets */
    .end .volume,
    .end .clock,
    .end .tray,
    .volume,
    .clock,
    .tray {
      background: transparent;
      background-color: transparent;
      color: #ffffff;
      padding: 2px 8px;
    }

    /* Force text and icon inheritance across all GTK children */
    .end label,
    .end image,
    .volume *,
    .clock *,
    .tray * {
      background: transparent;
      color: #ffffff;
    }

    .tray {
      padding: 2px 4px;
    }
  '';

  systemd.user.services.ironbar = {
    Unit = {
      Description = "Ironbar custom Wayland bar";
      After = ["graphical-session.target"];
      PartOf = ["graphical-session.target"];
    };
    Service = {
      ExecStart = "${pkgs.ironbar}/bin/ironbar";
      Restart = "on-failure";
      RestartSec = "1sec";

      # Force GTK4 onto its Cairo (CPU) renderer. Without this the journal shows
      # GDK bringing up the Vulkan backend and binding a real device:
      #   Vulkan: Using "AMD Radeon 880M Graphics (RADV STRIX1)"
      # so the bar held a full Vulkan device and showed up in amdgpu_top's
      # fdinfo as a GPU client (4 MiB VRAM / 8 MiB GTT). For a clock, a volume
      # readout and five workspace buttons that is pure overhead on a GPU whose
      # memory bus is shared with the CPU. Measured headroom for doing it on the
      # CPU instead: 28 MiB peak RSS and 491 ms of CPU over two minutes.
      Environment = ["GSK_RENDERER=cairo"];
    };
    Install = {
      WantedBy = ["hyprland-session.target"];
    };
  };

  # ---------------------------------------------------------------------------
  # LOW-LATENCY EDITOR (Neovim)
  # ---------------------------------------------------------------------------
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    withPython3 = false;
    withRuby = false;

    extraPackages = with pkgs; [
      nixd
      alejandra
      ripgrep
      fd
    ];

    plugins = with pkgs.vimPlugins; [
      nvim-treesitter.withAllGrammars
      nvim-lspconfig
      telescope-nvim
      plenary-nvim
    ];

    initLua = ''
      vim.opt.clipboard = "unnamedplus"
      vim.g.mapleader = " "
      vim.opt.number = true
      vim.opt.relativenumber = true
      vim.opt.shiftwidth = 2
      vim.opt.tabstop = 2
      vim.opt.expandtab = true
      vim.opt.updatetime = 50

      vim.lsp.config('nixd', {
        cmd = { "nixd" },
        settings = {
          nixd = {
            formatting = { command = { "alejandra" } },
          },
        },
      })
      vim.lsp.enable('nixd')

      vim.api.nvim_create_autocmd("BufWritePre", {
        pattern = "*.nix",
        callback = function()
          vim.lsp.buf.format()
        end,
      })

      local builtin = require('telescope.builtin')
      vim.keymap.set('n', '<leader>f', builtin.find_files, {})
      vim.keymap.set('n', '<leader>g', builtin.live_grep, {})
    '';
  };

  # ---------------------------------------------------------------------------
  # BROADCAST & CAPTURE PIPELINE (OBS Studio)
  # ---------------------------------------------------------------------------
  programs.obs-studio = {
    enable = true;
    plugins = with pkgs.obs-studio-plugins; [
      obs-vkcapture
      obs-pipewire-audio-capture
      obs-vaapi
      obs-gstreamer
      input-overlay
    ];
  };

  # ---------------------------------------------------------------------------
  # DECLARATIVE BROWSER (Firefox)
  # ---------------------------------------------------------------------------
  programs.firefox = {
    enable = true;
    configPath = "${config.xdg.configHome}/mozilla/firefox";

    policies = {
      DisableTelemetry = true;
      DisableFirefoxStudies = true;
      DisablePocket = true;
      OverrideFirstRunPage = "";
      OverridePostUpdatePage = "";

      EnableTrackingProtection = {
        Value = true;
        Locked = true;
        Cryptomining = true;
      };

      ExtensionSettings = {
        "*" = {installation_mode = "allowed";};
        "uBlock0@raymondhill.net" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi";
          installation_mode = "force_installed";
        };
        "{d8293796-0370-4f51-b845-89498a442750}" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/youtube-music-enhancer/latest.xpi";
          installation_mode = "force_installed";
        };
      };
    };

    profiles.crazycat = {
      id = 0;
      isDefault = true;

      settings = {
        "gfx.webrender.all" = true;
        "gfx.webrender.compositor" = true;
        "gfx.webrender.compositor.force-enabled" = true;
        "widget.use-aspect-ratio" = true;
        "widget.dmabuf.wayland-hardware-efficient" = true;
        "media.ffmpeg.vaapi.enabled" = true;
        "media.hardware-video-decoding.enabled" = true;
        "media.av1.enabled" = true;
        "layers.acceleration.force-enabled" = true;

        # 0 = unthrottled repaint; -1 = follow hardware vsync. Firefox holds
        # 58 MiB VRAM / 157 MiB GTT and sits in the background during play, so
        # unthrottled repaint is spending shared APU memory bandwidth on a
        # window nobody is looking at.
        "layout.frame_rate" = -1;
        "apz.overscroll.enabled" = true;
        "nglayout.initialpaint.delay" = 0;
        "browser.preferences.defaultPerformanceSettings.enabled" = false;
        "image.mem.shared" = true;

        "browser.cache.disk.enable" = true;
        "browser.cache.disk.capacity" = 1048576;
        "browser.cache.memory.enable" = true;

        "extensions.pocket.enabled" = false;
        "browser.newtabpage.activity-stream.showSponsored" = false;
        "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
        "browser.newtabpage.activity-stream.feeds.telemetry" = false;
        "toolkit.telemetry.enabled" = false;
        "browser.ping-centre.telemetry" = false;
        "browser.compactmode.show" = true;
        "browser.uidensity" = 1;
        "browser.tabs.firefox-view" = false;
      };
    };
  };

  # ---------------------------------------------------------------------------
  # USER-SPACE PACKAGES & LOW-LATENCY HELPERS
  # ---------------------------------------------------------------------------
  fonts.fontconfig.enable = true;

  home.packages = with pkgs; [
    nerd-fonts.fira-code
    pavucontrol
    deepfilternet
    lsp-plugins
    polkit_gnome
    docker-client
    playerctl
    overskride
    wineWow64Packages.staging
    winetricks
    protontricks
    grim
    slurp
    wl-clipboard
    satty
    adwaita-icon-theme
    hicolor-icon-theme
    obs-studio-plugins.obs-vkcapture
    libva-utils
    osu-lazer-bin
    celluloid
    claude-code
    tor-browser
    proton-vpn
    p7zip
    unrar
    ark
    pear-desktop
    (discord.override {
      withVencord = true;
      withOpenASAR = true;
    })

    (writeShellScriptBin "screenshot-region" ''
      SCREENSHOT_DIR="$HOME/Pictures/Screenshots"
      mkdir -p "$SCREENSHOT_DIR"
      FILENAME="$SCREENSHOT_DIR/$(date +'%Y-%m-%d_%H-%M-%S').png"

      ${pkgs.grim}/bin/grim -g "$(${pkgs.slurp}/bin/slurp)" - | tee "$FILENAME" | ${pkgs.wl-clipboard}/bin/wl-copy
      if command -v notify-send &> /dev/null; then
        notify-send "Screenshot Captured" "Saved to $FILENAME and copied to clipboard." --icon=camera
      fi
    '')

    (writeShellScriptBin "osu-launcher" ''
      export WINEPREFIX="$HOME/.wine-osu"
      export STAGING_AUDIO_DURATION="10000"
      export STEAM_COMPAT_DATA_PATH="$HOME/.wine-osu"
      export PIPEWIRE_LATENCY="64/48000"
      export DXVK_HUD=0

      server_input=$(echo "" | ${pkgs.fuzzel}/bin/fuzzel -d -p "osu! DevServer (Leave blank for Bancho): ")

      if [ -n "$server_input" ]; then
        exec obs-gamecapture ${pkgs.wineWow64Packages.staging}/bin/wine "$HOME/Games/osu/osu!.exe" -devserver "$server_input" "$@"
      else
        exec obs-gamecapture ${pkgs.wineWow64Packages.staging}/bin/wine "$HOME/Games/osu/osu!.exe" "$@"
      fi
    '')
  ];

  services.swayosd = {
    enable = true;
    stylePath = null;
  };

  # ---------------------------------------------------------------------------
  # DYNAMIC OUTPUT MANAGEMENT (Kanshi Daemon)
  # ---------------------------------------------------------------------------
  services.kanshi = {
    enable = true;
    systemdTarget = "hyprland-session.target";
    settings = [
      {
        profile = {
          name = "docked";
          outputs = [
            {
              criteria = "eDP-1";
              status = "disable";
            }
            {
              criteria = "BNQ XL2586X+ EB3CR02979SL0";
              mode = "1920x1080@599.94Hz";
              position = "0,0";
              scale = 1.0;
              status = "enable";
            }
          ];
        };
      }
      {
        profile = {
          name = "undocked";
          outputs = [
            {
              criteria = "eDP-1";
              mode = "2240x1400@60.00Hz";
              position = "0,0";
              scale = 1.4583334;
              status = "enable";
            }
          ];
        };
      }
    ];
  };

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    settings = {
      "*" = {
        ServerAliveInterval = 30;
        ServerAliveCountMax = 3;
        TCPKeepAlive = "yes";
      };
    };
  };

  # ---------------------------------------------------------------------------
  # XDG MIME ROUTING & THEMES
  # ---------------------------------------------------------------------------
  xdg.desktopEntries = {
    osu-stable = {
      name = "osu!stable";
      exec = "osu-launcher %U";
      icon = "osu!";
      comment = "osu! stable";
      terminal = false;
      categories = ["Game"];
      mimeType = [
        "application/x-osu-beatmap"
        "application/x-osu-skin"
        "application/x-osu-replay"
        "application/x-extension-osz"
        "application/x-extension-osk"
        "application/x-extension-osr"
      ];
    };
  };

  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "application/x-osu-beatmap" = "osu-stable.desktop";
      "application/x-osu-skin" = "osu-stable.desktop";
      "application/x-osu-replay" = "osu-stable.desktop";
      "application/x-extension-osz" = "osu-stable.desktop";
      "application/x-extension-osk" = "osu-stable.desktop";
      "application/x-extension-osr" = "osu-stable.desktop";
    };
  };

  gtk = {
    enable = true;
    gtk4.theme = null;
    theme = {
      name = "Adwaita-dark";
      package = pkgs.gnome-themes-extra;
    };
    iconTheme = {
      name = "Adwaita";
      package = pkgs.adwaita-icon-theme;
    };
  };

  home.sessionVariables = {
    MOZ_USE_XDG = "1";
  };

  home.stateVersion = "25.11";
}
